apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component--nuky
  namespace: build-templates-e2e
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-app-esrb
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component--nuky
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component--nuky-
      labels:
        build.appstudio.openshift.io/application: test-app-esrb
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component--nuky
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: build-templates-e2e
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic
      - name: output-image
        value: quay.io/redhat-appstudio/test-images:ad16b5dadb364034a3ba95653d4ed5be-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/pull-request-builds:base-655b65c0311b0d8c010decab98f3e54e3535f326
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: test-component--nuky/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
